### PR TITLE
Added intro screen that lets users choose the data directory for DeepOnion

### PR DESCRIPTION
**Pull request by fuss132**
When launching DeepOnion wallet for the first time (or the data directory has been deleted) an intro screen is shown that lets the user choose a data directory. Enough with no more storage left in the appdata folder.

I adopted this from the bitcoin core intro screen but had to modify it heavily as we have a different code base. I only tested this on Ubuntu, please do your own tests before merging it as this is quite critical if something goes wrong.

bildschirmfoto von 2018-04-15 11-33-26

### CODE REVIEW

**Comment by brakmic** [comment]
@fuss132 
Many thanks 👍 
I'm just compiling your code on Win & Mac and will give you an update shortly. 
Btw. do you have an account in our forums?
We've found a "fuss132" there but we are not sure if this is you or someone else pretending to be you.
I'd like to recommend you for a reward, but without a proper account & DO-address it'd be very hard to find you 😸 

Cheers,

**Comment by fuss132** [comment]
I do, but it's a different username and I don't want to connect both usernames. It was me registering the fuss132 nickname in the forums last week to prevent someone else doing this. After the airdrop ends next week I will switch to the fuss132 handle.

**Comment by brakmic** [comment]
@fuss132 

So, I fixed some paths in the Qt.pro file for Windows build.
Will now test Mac build. 

Ragarding the rewards, well, no problem. If you want to receive them you only have to write to one of our mods who goes by the name *bykardinal*. He already knows the story from GitHub. 

Also, you could join us on Slack. Maybe you're interested in working as a team member. I could send you an invitation link, if you're interested.

I'm now going back to complete Mac testing. Windows binary looks good!

**Comment by brakmic** [comment]
Mac binary also looks good!
Excellent! Nice work! 
Many thanks! ❤️

**Comment by fuss132** [comment]
I would definitely be interested to get involved, I'll follow you in the forums with the fuss132 username later so we can talk over there. Hoping to push a new PR before :smile:

**Comment by brakmic** [comment]
@fuss132 

Great then let's continue our communication there. I'll send you the invitation link to our Slack. 
See you there.

**Comment by aitorp6** [comment]
@brakmic do you think that I am able to join also to that Slack chat? I would like to continue contributing to this project.

**Comment by brakmic** [comment]
@aitorp6 
Of course. 
I'll send you an invitation via our forum.

**Pull request merged**
