### PR TITLE
Added menu entry to open DeepOnion.conf file with the system default editor

### PR DESCRIPTION
**Pull request by aitorp6**
Hi there

I have added a new entry in the **Settings** menu to open **DeepOnion.conf** file with the system default file editor. I think that it could be helpful when one wants to edit this file, just by clocking there the editor opens with the desired file.

I have tested it on Linux (but not in Windows or MAC) and works fine. I think that it should work properly on Windows or Mac because the piece of code open the editor is analogous to that one that opens the Debug log file with the default editor.    

img

### CODE REVIEW

**Comment by brakmic** [comment]
Thanks for the PR, but we already instantiate RPCConsole in the BitcoinGUI constructor, so I don't think you need another 

```
 rpcConsole = new RPCConsole(this);
```

on [line 372](https://github.com/deeponion/deeponion/pull/90/commits/15ed17f407275531517b17c21af38a02e7490ab0#diff-0db7dd184df07a48c307ccc182021a68R372).

But the idea is good and many other wallets have the same functionality.

**Comment by aitorp6** [comment]
Thank you for your feedback. I will check it later.

**Comment by aitorp6** [comment]
Now is fixed, I think.

**Comment by brakmic** [comment]
Many thanks!

**Comment by brakmic** [comment]
@aitorp6 
I added a screenshot to your initial posting.

**Comment by aitorp6** [comment]
Thank you, that will help to understand the pull request.

**Pull request merged**
