### PR TITLE
Fixed issue: undefined reference to qInitResources_bitcoin()

### PR DESCRIPTION
**Pull request by aitorp6**
Hi.

This fixes the following issues: https://github.com/deeponion/deeponion/issues/75 and https://github.com/deeponion/deeponion/issues/106

It have been tested on Linux and MAC, test that it works fine on Windows.

### CODE REVIEW

**Comment by deeponion** [comment]
nice and interesting... I've been using this to fix the issue:
https://github.com/deeponion/deeponion/issues/75

**Comment by aitorp6** [comment]
I used the same trick, but this commit fixes that issue. As I said, it should be tested on Windows.

**Comment by chisNaN** [comment]
Hello @aitorp6 
Thanks for the PR, will test that ASAP on a macbook 12 3rd gen

**Comment by chisNaN** [comment]
I confirm the `src/qt/DeepOnion-qt` was successfully generated thanks to changes by @aitorp6 
but now i don't understand why the `DeepOnion.conf` file requires some additional paramaters like `rpcuser` and `rpcpassword` sot that the wallet keep running on macOs?

On windows my config file just contains node addresses and it run "correctly".
My questions are:
Are these variables set somewhere else on windows?
If not is it bad practice not to have them set on the `DeepOnion.conf` file ? (the consequences)
Thanks

**Comment by fuss132** [comment]
@aitorp6 Are you sure this will work forever? (Haven't tried it yet, would be nice if it does) I currently have to edit the file to change the filehash every now and then. But only at 20% of the time

**Comment by aitorp6** [comment]
I hope so, but I'm not sure.

**Comment by deeponion** [comment]
on windows i never see this issue, the issue only occurs in mac build or linux build.

**Pull request merged**
